apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/redis/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-sc
